before:
  hooks:
    - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - '386'
    - arm
    - arm64

  ignore:
    - goos: darwin
      goarch: '386'
    - goos: windows
      goarch: 'arm'
    - goos: windows
      goarch: 'arm64'

  binary: '{{ .ProjectName }}'
  main: cmd/pdtm/pdtm.go

archives:
- format: zip
  replacements:
      darwin: macOS

checksum:
  algorithm: sha256

# Skipping annoucement for now
# announce:
#   slack:
#     enabled: true
#     channel: '#release'
#     username: GoReleaser
#     message_template: '{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}'